In [2]:
import numpy as np

#### 행렬곱
- 앞 행렬의 열의 수가 뒤 행렬의 행의 수와 일치해야 한다.
- 교환 법칙이 성립하지 않음 : (A @ B) (B @ A)
- 분배법칙은 성립함 : A @ (B + C) A @ B + A @ C
- 전치 연산도 덧셈, 뺄셈에 대한 분배 법칙 성립 : (A + B).T A.T + B.T
- 전치 연산과 곱셈의 경우에는 분배 법칙이 성립하지만, 전치 연산이 분배되면서 곱셈의 순서가 바뀜 (A @ B).T vs B.T @ A.T

#### 과제1_0420.
앞에 언급한 사항들의 사례를 작성해서 의미를 확인하고 설명하세요.

In [3]:
A = np.array([[1, 2, 3],[4, 5, 6]])

B = np.array([[7, 8, 9],[10, 11, 12],[13, 14, 15]])

np.dot(A,B)

# A는 2 x 3, B는 3 x 3 내적하려면 A의 열의 수와 B의 행의 수가 일치해야한다. -> 새로운 값은 2 x 3의 값이 됨
# 이 사례에서 교환 법칙을 따져보면
# B는 3 x 3 A는 2 x 3, B의 열의 수 3인데 A는 2행으로 일치하지 않아서 교환법칙은 성립하지 않고, 
# 일치하더라도 행렬의 순서에 따라 곱하는게 다르기 때문에 교환법칙은 성립하지 않는다.


array([[ 66,  72,  78],
       [156, 171, 186]])

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# (A + B)C와 AC + BC의 결과 비교
result1 = np.dot((A + B), C)
result2 = np.dot(A, C) + np.dot(B, C)

print(result1,'\n')
print(result2)

# 분배법칙은 성립함

[[142 156]
 [222 244]] 

[[142 156]
 [222 244]]


In [5]:
# 전치 연산도 덧셈, 뺄셈에 대한 분배 법칙 성립

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print((A + B).T) 
print(A.T + B.T)

[[ 6 10]
 [ 8 12]]
[[ 6 10]
 [ 8 12]]


In [6]:
# 전치 연산과 곱셈의 경우에는 분배 법칙이 성립하지만, 전치 연산이 분배되면서 곱셈의 순서가 바뀜 (A @ B).T vs B.T @ A.T

print((A @ B).T,'\n')
print(A.T @ B.T,'\n')
print(B.T @ A.T)

# 전치 연산은 행과 열을 바꾸는 연산이기 때문에, 
# 행렬의 내적에서는 전치 연산이 적용된 행렬의 순서가 바뀌면서 곱셈의 순서도 바뀐다.

[[19 43]
 [22 50]] 

[[23 31]
 [34 46]] 

[[19 43]
 [22 50]]


#### 과제2_0420
배열 e의 행렬식을 구하면 에러가 발생됩니다. 행렬식의 의미를 감안하여 e 행렬을 수정하여 다음사항을 수행하세요

- 행렬식을 계산하세요
- 역행렬을 구하세요
- 역행렬

In [7]:
e = np.array([[1,0,0],[0,1,0]])
np.linalg.det(e)

LinAlgError: Last 2 dimensions of the array must be square

In [11]:
# 오류가 나는 이유는 주어진 'e' 배열이 정사각 행렬이 아니기 때문
# 항등행렬은 반드시 행과 열이 같아야 함!!
# 그래서 행렬식을 계산하려면 새로운 배열을 만들어야 한다. 

e = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(e,'\n')
e_inv = np.linalg.inv(e)
print(e_inv)

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
