#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html

Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

In [4]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

# 연산하는 시간 체크
%time for _ in range(10):my_array2 = my_arr * 2 # _무시하는 숫자 표현

Wall time: 15 ms


In [6]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]
    
    # 시간이 덜 걸리는 배열이 효과적이다. 

Wall time: 753 ms


In [10]:
# 배열 연산
np.random.seed(0)            # 계속 랜덤으로 뽑히는 걸 방지
data = np.random.randn(2,3)  # 정규분포를 이루는 숫자 중 2행 3열로 뽑겠다.
print(data,'\n')
print(data * 10, '\n')       # 데이터 각각에 10 이 곱해짐
print(data + data) 


[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]] 

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]


In [13]:
# 데이터의 크기를 보려면

print(data.shape)   # 데이터의 크기
print(data.dtype)  # 데이터의 자료형
print(data.ndim)   # 차원

(2, 3)
float64
2


In [14]:
# 배열 생성
# 1차원

data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
print(arr1,type(arr1))

[6 7 5 8 0 1] <class 'numpy.ndarray'>


In [17]:
# 2차원

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2,type(arr2),'\n')
print(arr2.shape,'\n')
print(arr2.ndim,'\n')
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 

(2, 4) 

2 

int32


In [18]:
# 3차원

data3 = [[[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]],
        [[1,2,3,4,5],[6,7,8,9,10]]]
arr3 = np.array(data3)
print(arr3,type(arr3),'\n')
print(arr3.shape,'\n')
print(arr3.ndim,'\n')
print(arr3.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'> 

(3, 2, 5) 

3 

int32


배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [24]:
print(np.zeros(10),'\n')
print(np.zeros((3,5)),'\n')
print(np.zeros((2,3,2)),'\n')  # (2차원 배열 2개이고, 3행, 2열)

print(np.ones(10),'\n')
print(np.ones((3,5)),'\n')
print(np.ones((2,3,2)))  # (2차원 배열 2개이고, 3행, 2열)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [42]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

a = np.arange(10).reshape(2,5)
print(a,'\n')

print(np.zeros_like(a),'\n')

print(np.ones_like(a),'\n')

print(np.full_like(a,2))

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 0 0 0 0]
 [0 0 0 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[2 2 2 2 2]
 [2 2 2 2 2]]


In [30]:
# arange 함수 : 파이썬의 range 함수의 배열 버전
ar = np.arange(15) # 0부터 14까지 뽑아줌
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
# reshape 함수 원하는 차원으로 바꿔주는 것
ar.reshape(3,5)   # 대신 나눠 떨어지는 것으로 차원을 정해야함. 

ar.reshape(1,15)  # 2차원 [[]] 대가로 두개니까

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [35]:
# Q. array1에 reshape 함수를 이용(5,2)배열을 생성하고 형태를 같이 출력하세요.

array1 = np.arange(10)

b = array1.reshape(5,2)
print(b,type(b))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>


In [38]:
# Q. ar에 reshpae() 함수 이용, 1차원, 2차원, 3차원 배열 생성

ar = np.arange(12)
print(ar,'\n')
print(ar.reshape(3,4),'\n')
print(ar.reshape(3,2,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [42]:
# 차원 변경

ar1 = np.arange(30)
print('1->2,3차원')
ar12 = ar1.reshape(2,-1)    # 2행으로 하고 나머지는 계산해서 알아서 해줘
ar13 = ar1.reshape(-1,2,5)  # 2행 5열로 할 건데 나머지는 너가 알아서 계산해서 해줘
print(ar12,'\n')
print(ar13,'\n')

1->2,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 



In [43]:
print('2->1,3차원')

print(ar12,'\n')
ar21 = ar12.reshape(-1,)  # 2차원에서 1차원으로 바꾸는 방법
ar23 = ar12.reshape(-1,2,5)
print(ar21,'\n')
print(ar23,'\n')

2->1,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 



In [34]:
ar3 = np.arange(30).reshape(3,2,5)
print(ar3,type(ar3),'\n')
l3 = ar3.tolist()    # 배열을 리스트로 변경 tolist()
print(l3,type(l3))

# 리스트를 배열로 바꾸려면 array
t_ar = np.array(l3)
print(t_ar,type(t_ar))


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'> 

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]] <class 'list'>
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'>


행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [47]:
# 정방행렬 : 행과 열의 수가 같음
# 넘파이에서 정방행렬은 full 함수로 만들 수 있음 ((행,열),채울숫자)

a = np.full((2,2),7)
a

array([[7, 7],
       [7, 7]])

In [48]:
# 항등행렬, 단위행렬  : 대각선이 1이고 나머지 다 영인 것 -> 행과 열의 수가 같으니까 정방행렬이라고 할 수 있음

ar = np.eye(3) # 대각선의 갯수 3
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
# 대각행렬

diag_mat = np.diag([1,2,3,4,5])  # 대각선에 넣고싶은 숫자들. 나머지는 다 영
diag_mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [52]:
# 삼각행렬
upper_tri_mat = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(upper_tri_mat)

[[1 2 3]
 [0 5 6]
 [0 0 9]]


In [43]:
# [과제] 하삼각행렬을 생성하세요.

lower_tri_mat = np.tril([[1,2,3],[4,5,6],[7,8,9]])
print(lower_tri_mat)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [39]:
# 전치행렬 : 원래의 행렬에서 행과 열을 바꾼 행렬을 의미
# 3행 2열을 전치행렬하면 2행 3열이 됨
import numpy as np

mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat,'\n')
transpose_mat = mat.T   # 전치행렬로 만드는 것.
print(transpose_mat)

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]]


#### 직교행렬
- 행과 열이 서로 직교하는 정방행렬.
- 모든 열벡터와 행벡터가 서로 직교하고 크기가 1인 단위벡터로 이루어짐
- np.linalg.qr() 함수를 사용하여 QR 분행 수행하여 직교행렬을 추출
- q를 추출하여 직교행렬 orth_mat을 만든다
- np.dot(orth_mat,orth_mat.T)를 계산하여 직교성을 검증
- np.allclose() 함수로 두 행렬이 동일한지 검사. True를 반환하면 두 행렬은 동일

In [4]:
# A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬
mat = np.random.randn(3,3)
print(mat)

# qr 분해
q,r = np.linalg.qr(mat)

# 직교행렬 추출
orth_mat = q
print(orth_mat)

# 직교성 검증
print(np.allclose(np.dot(orth_mat,orth_mat.T),np.eye(3)))

[[ 0.00462903 -2.17545745 -1.2904828 ]
 [ 0.59131476  0.56577146  1.66150262]
 [-0.22155993  0.05267523 -0.4375922 ]]
[[-0.00733048  0.99356793  0.11300019]
 [-0.93639932 -0.04646982  0.34784605]
 [ 0.35085978 -0.10326342  0.93071697]]
True


In [26]:
# 인덱싱, 슬라이싱
ar2 = np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(ar2[2])    # 인덱스 2번째 행
print(ar2[0][2]) # 인덱스 0번째 행의 인덱스 2번째 열
print(ar2[0,2])  # 인덱스 0번째 행의 인덱스 2번째 열

[7 8 9]
3
3


In [29]:
ar = np.arange(20).reshape(5,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
ar[:2,1:] # 인덱스 0 ~ 1번째 행에서 인덱스 1번째에서 끝까지의 열

array([[1, 2, 3],
       [5, 6, 7]])

# Q. ar에서 슬라이싱을 사용해서 아래와 같이 출력하세요.

[[1 2]<br>
 [4 5]] 

[[4 5 6]<br>
 [7 8 9]] 
<br><br>
[[4 5 6]<br>
 [7 8 9]] 

[[1 2 3]<br>
 [4 5 6]<br>
 [7 8 9]] 
<br><br>
[[2 3]<br>
 [5 6]] 
<br><br>
[1 4]

ar =<br> 
array([[1, 2, 3],<br>
       [4, 5, 6],<br>
       [7, 8, 9]])

In [31]:
ar = np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(ar[:2,:2],'\n')
print(ar[1:],'\n')
print(ar[1:,:],'\n')
print(ar,'\n')
print(ar[:2,1:],'\n')
print(ar[:2,0])    # 이건 나중에 생각 안 날 듯

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[1 4]


[과제] ar에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
- [3, 6]
- [[1, 2], [4, 5]]
- [[1, 2, 3], [4, 5, 6]]

In [44]:
ar2 =np.arange(1,10).reshape(3,3)
print(ar2, '\n')

print(ar2[:2,2].tolist())        #[3, 6]
print(ar2[:2,:2].tolist())       #[[1, 2], [4, 5]]
print(ar2[:2,:].tolist())        #[[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [12]:
# Boolean indexing
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ar[ar > 5]

array([6, 7, 8, 9])

In [16]:
# Q. 1 ~ 14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱스로 출력하세요.

array_e = np.arange(1,15)
array_e[(array_e/2) > 5]

array([11, 12, 13, 14])

In [17]:
# arr에서 0.5보다 큰 수를 출력하세요.

np.random.seed(0)
arr = np.random.randn(30)
arr[arr>0.5]

array([1.76405235, 0.97873798, 2.2408932 , 1.86755799, 0.95008842,
       1.45427351, 0.76103773, 1.49407907, 0.6536186 , 0.8644362 ,
       2.26975462, 1.53277921, 1.46935877])

In [18]:
# Q. data에서 3의 배수인 것 수만 출력하세요.

np.random.seed(0)
data = np.arange(30)
data[data%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.

np.where(condition)은 
- condition 배열의 요소가 True인 인덱스를 반환하는 함수입니다. 
- condition 배열은 bool 타입이어야 하며, 반환값은 tuple 타입으로 (array of row indices, array of column indices)의 형태로 반환

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
array = np.where(arr > 5)
array


# 아래 인덱스 읽는 방법
# (array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2])
#         행 인덱스                         열 인덱스       

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [67]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0, 1, 0) # np.where(조건, 참이면 반영되는 값, False라면 반영되는 값)

array([1, 1, 0, 0, 1, 0])

In [2]:
import numpy as np

a = np.array([1,2,0,0,4,0])
index = np.where(a != 0)           # 조건을 만족하는 인덱스 반환
print(index)                     
print(index[0])                                 

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [51]:
a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a)
print(nz[0])

[0 1 4]


In [20]:
# any 메서드 : 하나 이상의 값이 True인지 검사

bools.any()

True

In [21]:
# all 메서드 : 모든 원소가 True인지 검사

bools.all()

False

In [57]:
# Q. arr에서 0보다 크면 2, 아니면 -2로 변경하세요.

arr = np.random.randn(4,4)
arr

array([[-0.70875832,  0.10802378, -1.00098274, -0.81428464],
       [-0.52178746,  1.82800718,  1.62076076, -1.77173942],
       [ 0.4067365 ,  0.82184556, -0.34165133,  0.5365236 ],
       [-2.63623338,  1.61189974,  0.29513136, -0.1302978 ]])

In [56]:
# np.where(조건, 참이면 반영되는 값, False라면 반영되는 값) 값 변경
np.where(arr > 0, 2, -2)

array([[-2, -2, -2,  2],
       [-2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2, -2,  2,  2]])

In [59]:
# Q. arr의 모든 양수를 2로 바꾸세요.
np.where(arr > 0 , 2, arr)  # 음수라면 그대로 반영

array([[-0.70875832,  2.        , -1.00098274, -0.81428464],
       [-0.52178746,  2.        ,  2.        , -1.77173942],
       [ 2.        ,  2.        , -0.34165133,  2.        ],
       [-2.63623338,  2.        ,  2.        , -0.1302978 ]])

In [60]:
# np.sort() : 복사본을 반환. 원본 미반영. 순서대로 

np.random.seed(0)
arr = np.random.randint(1,100,size=10) # 1~99에서 10개 뽑기
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [27]:
print(np.sort(arr))
print(arr)

[10 22 37 45 48 65 68 68 84 88]
[45 48 65 68 68 10 84 22 37 88]


In [28]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [68]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬 수행
ar2 = np.array([[8,12],
              [7,1]])
print(ar2,'\n')
print(np.sort(ar2,axis=0),'\n') # axis=0 열방향
print(np.sort(ar2,axis=1))      # axis=1 행방향

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [30]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr = np.random.randint(10,size=10)
print(arr)
arr.sort()
arr

[5 0 3 3 7 9 3 5 2 4]


array([0, 2, 3, 3, 3, 4, 5, 5, 7, 9])

In [70]:
arr = np.random.randint(10,size=(10,10))   # 1 ~ 9까지, 10행 10열
arr

array([[9, 2, 3, 3, 2, 3, 4, 1, 2, 9],
       [1, 4, 6, 8, 2, 3, 0, 0, 6, 0],
       [6, 3, 3, 8, 8, 8, 2, 3, 2, 0],
       [8, 8, 3, 8, 2, 8, 4, 3, 0, 4],
       [3, 6, 9, 8, 0, 8, 5, 9, 0, 9],
       [6, 5, 3, 1, 8, 0, 4, 9, 6, 5],
       [7, 8, 8, 9, 2, 8, 6, 6, 9, 1],
       [6, 8, 8, 3, 2, 3, 6, 3, 6, 5],
       [7, 0, 8, 4, 6, 5, 8, 2, 3, 9],
       [7, 5, 3, 4, 5, 3, 3, 7, 9, 9]])

In [32]:
# 다차원 배열의 정렬은 sort 메서드에 넘긴 축에 따라 1차원 부분을 정렬

arr.sort(1)
# arr.sort(0) # 행방향
arr.sort(1) # 열방향. Default
arr

array([[1, 1, 6, 6, 7, 7, 7, 8, 8, 8],
       [0, 0, 3, 3, 4, 5, 5, 8, 9, 9],
       [0, 1, 1, 2, 3, 3, 3, 3, 7, 8],
       [0, 0, 2, 2, 3, 4, 7, 7, 9, 9],
       [0, 1, 4, 4, 4, 5, 5, 6, 8, 9],
       [1, 1, 2, 3, 6, 7, 7, 8, 9, 9],
       [0, 3, 3, 4, 4, 4, 4, 5, 6, 9],
       [0, 1, 3, 4, 4, 4, 5, 5, 7, 8],
       [0, 0, 1, 2, 2, 3, 4, 5, 5, 9],
       [0, 0, 0, 2, 2, 3, 5, 7, 7, 9]])

In [71]:
# 정렬된 행렬의 인덱스 반환 : 원본 기준 행렬의 원소에 대한 정렬 인덱스를 필요로 할 때 np.argsort()

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
sort_indices

[3 1 9 5]


array([1, 0, 3, 2], dtype=int64)

In [34]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식. npy 파일로 저장

arr= np.arange(10)
np.save('some_array',arr)

np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['a']

array([[9, 2, 3, 3, 2, 3, 4, 1, 2, 9],
       [1, 4, 6, 8, 2, 3, 0, 0, 6, 0],
       [6, 3, 3, 8, 8, 8, 2, 3, 2, 0],
       [8, 8, 3, 8, 2, 8, 4, 3, 0, 4],
       [3, 6, 9, 8, 0, 8, 5, 9, 0, 9],
       [6, 5, 3, 1, 8, 0, 4, 9, 6, 5],
       [7, 8, 8, 9, 2, 8, 6, 6, 9, 1],
       [6, 8, 8, 3, 2, 3, 6, 3, 6, 5],
       [7, 0, 8, 4, 6, 5, 8, 2, 3, 9],
       [7, 5, 3, 4, 5, 3, 3, 7, 9, 9]])

In [36]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]를 출력하세요

a = np.ones(10,dtype=int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[:] = arr%2   
arr

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

[과제] 1 ~ 100을 아래와 같이 출력하세요<br>
[[  1   2   3   4   5   6   7   8   9  10]<br>
 [ 20  19  18  17  16  15  14  13  12  11]<br>
 [ 21  22  23  24  25  26  27  28  29  30]<br>
 [ 40  39  38  37  36  35  34  33  32  31]<br>
 [ 41  42  43  44  45  46  47  48  49  50]<br>
 [ 60  59  58  57  56  55  54  53  52  51]<br>
 [ 61  62  63  64  65  66  67  68  69  70]<br>
 [ 80  79  78  77  76  75  74  73  72  71]<br>
 [ 81  82  83  84  85  86  87  88  89  90]<br>
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

In [5]:
arr = np.arange(1,101).reshape(10,10)

for i in range(1,10,2):
    arr[i]=arr[i][::-1]

print(arr, type(arr))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [74]:
arr = np.arange(1,101).reshape(10,10)
arr[1::2] = arr[1::2, ::-1]     # 행을 2번씩 건너서, 열을 거꾸로 하겠다.
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

[과제] np.ones((10,10))을 아래와 같이 출력하세요<br>
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],<br>
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
arr = np.ones((10,10))
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

[과제] np.ones((5,5))을 아래와 같이 출력하세요<br>
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],<br>
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],<br>
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],<br>
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],<br>
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],<br>
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],<br>
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],<br>
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],<br>
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
arr=np.ones((5,5))

v=np.zeros((2,5))
h=np.zeros((9,2))

arr2=np.vstack((arr,v))      # arr 아래에 v 붙이기
arr2=np.vstack((v,arr2))
#print(arr2)

arr2=np.hstack((h,arr2))     # h 옆에 arr2 붙이기
arr2=np.hstack((arr2,h))
print(arr2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
arr = np.zeros((10,10))
arr[2:8,2:8] = 1  
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

[과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)<br>
array([[0, 1, 0, 1, 0, 1, 0, 1],<br>
       [1, 0, 1, 0, 1, 0, 1, 0],<br>
       [0, 1, 0, 1, 0, 1, 0, 1],<br>
       [1, 0, 1, 0, 1, 0, 1, 0],<br>
       [0, 1, 0, 1, 0, 1, 0, 1],<br>
       [1, 0, 1, 0, 1, 0, 1, 0],<br>
       [0, 1, 0, 1, 0, 1, 0, 1],<br>
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [19]:
arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            arr[i][j] = 1
print(arr)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
arr=np.zeros((8,8))

for i in range(8):
    if i%2==0:
        arr[i][1::2]=1     # 짝수 번째 줄 0101010
    else:
        arr[i][0::2]=1     # 홀수 번째 줄 1010101
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [21]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

[과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요<br>
np.arange(336).reshape(6,7,8)

In [23]:
# unravel_index() 함수는 1차원 배열에서 인덱스를 다차원 인덱스 튜플로 반환해주는 함수

arr = np.arange(336).reshape(6,7,8)
np.unravel_index(100,arr.shape)

(1, 5, 4)

In [77]:
np.arange(336).reshape(6,7,8)

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15