In [4]:
import pandas as pd                            # pd에 판다스를 가져옵니다
st1 = pd.Series({'국어':100,'영어':80,'수학':90}) # 딕셔너리를 시리즈로 바꿔 str1에 저장
st2 = pd.Series({'국어':90,'영어':80,'수학':80})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)        # 소수점 둘째자리까지 표현 round(나눌것,소수점자리)

print(add,'\n')
print(sub,'\n')
print(mul,'\n')
print(div)

국어    190
영어    160
수학    170
dtype: int64 

국어    10
영어     0
수학    10
dtype: int64 

국어    9000
영어    6400
수학    7200
dtype: int64 

국어    1.11
영어    1.00
수학    1.12
dtype: float64


In [5]:
df = pd.concat([add,sub,mul,div],axis=1)  
# 데이터프레임 붙이기. 
# pd.concat(데이터프레임리스트, axis=0 행방향(위아래)로 데이터프레임 이어붙인다.)
# 열방향axis=1(좌우)
df

0   1     2     3
국어  190  10  9000  1.11
영어  160   0  6400  1.00
수학  170  10  7200  1.12

In [6]:
result = pd.DataFrame([add,sub,mul,div],
                      index=['덧셈','뺄셈','곱셈','나눗셈'])
# result = pd.DataFrame([add,sub,mul,div])
result

국어      영어       수학
덧셈    190.00   160.0   170.00
뺄셈     10.00     0.0    10.00
곱셈   9000.00  6400.0  7200.00
나눗셈     1.11     1.0     1.12

In [22]:
import numpy as np
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1/st2),2)

# result = pd.DataFrame([add,sub,mul,div],index=[b'덧셈','뺄셈','곱셈','나눗셈'])
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
# b를 왜 붙인거지?
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [20]:
np.arange(12)  # 배열 나타내기

# np.arange(3) 의 경우 stop 매개변수의 값만 전달되었으므로 [0, 3) 의 반열린구간에서 0을 시작으로 1 간격으로 떨어진 수들을 array [0, 1, 2]의 형태로 반환함을 볼 수 있다.

# np.arange(3.0) 의 경우 dtype 의 주어지지 않았지만, 전달된 stop 매개변수의 값 0.3 으로 부터 정수가 아닌 실수값임을 추론하게 되고, 
# 그 결과 array [0., 1., 2.] 이 반환됨을 볼 수 있다.

# np.arange(3, 7) 의 경우 start=3, stop=7 이 주어진 경우로 3을 시작으로 1 간격으로 떨어진 수들을 
# array [3, 4, 5, 6] 의 형태로 반환함을 볼 수 있다.

# np.arange(3, 7, 2) 의 경우 start=3, stop=7, step=2 이므로 
# array[3, 5] 의 형태로 반환함을 볼 수 있다. 7의 경우 반열린구간 [3, 7) 에 포함되지 않기 때문에 결과 array 에 포함되지 않는다.  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
np.arange(12).reshape(3,4)
# n차원 배열의 형태 변경
# reshape(행,열)? 1차원 배열인 np를 2차원으로 변경한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

df2.loc[1,'b'] = np.nan
print(df1,'\n')
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [16]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [21]:
# fill_value() # 매칭되지 않는 키는 0으로 치환 (원본 데이터 손실 방지)
# Q. df2의 NaN 값을 0으로 대체 후 사칙연산을 수행하세요.

add_data = df1.add(df2,fill_value=0)
sub_data = df1.sub(df2,fill_value=0)
mul_data = df1.mul(df2,fill_value=0)
div_data = df1.div(df2,fill_value=0)

print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0 

      a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0 

      a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0 

     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8       inf  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0


#### 브로드캐스팅(Broadcasting)

- 데이터 프레임과 데이터 프레임 간의 연산은 오류가 남.
- 데이터프레임이 한 행일 경우에는 [[]] 두번 해줘야 함
- 데이터 프레임과 시리즈일 때 가능/ 서로 다른 크기의 넌파이에서도 가능

In [23]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [25]:
arr[0]           # [행,열]

array([0., 1., 2., 3.])

In [60]:
# broadcasting 
arr - arr[0]            # 서로 다른 크기의 배열을 계산하는 것. 즉, arr[0]을 arr의 행만큼 확대해서 계산해줌

# array([[ 0.,  1.,  2.,  3.],               -     array([0., 1., 2., 3.]) 
#        [ 4.,  5.,  6.,  7.],               -     array([0., 1., 2., 3.])
#        [ 8.,  9., 10., 11.]])              -     array([0., 1., 2., 3.])

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [30]:
# DataFrame과 Series간 연산
# step1
df = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b     d     e
서울  0.0   1.0   2.0
부산  3.0   4.0   5.0
인천  6.0   7.0   8.0
대구  9.0  10.0  11.0

In [31]:
# step2
sr = df.iloc[0]
sr

b    0.0
d    1.0
e    2.0
Name: 서울, dtype: float64

In [32]:
# step 연산
df - sr

b    d    e
서울  0.0  0.0  0.0
부산  3.0  3.0  3.0
인천  6.0  6.0  6.0
대구  9.0  9.0  9.0

In [49]:
# 함수 적용과 매핑
# randn은 표준정규분포에서 난수 생성
df = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                 index = ['서울','부산','인천','대구'])
df

b         d         e
서울 -0.159486  0.381123 -1.208001
부산  0.185892  0.377361 -0.651444
인천 -1.002547 -0.402731  0.016607
대구  0.069345 -0.523295  0.549448

In [50]:
np.abs(df)                  # 절대값

b         d         e
서울  0.159486  0.381123  1.208001
부산  0.185892  0.377361  0.651444
인천  1.002547  0.402731  0.016607
대구  0.069345  0.523295  0.549448

커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용

- map함수 : DataFrame 타입이 아니라, 반드시 Series 타입에서만 사용
- apply함수 : 커스텀 함수를 사용하기 위해 DataFrame에서 복수 개의 컬럼이 필요하다면, apply함수를 사용
- applymap함수 : DataFrame클래스의 함수이긴 하나, 위의 apply함수처럼 각 row(axis=1)나 각 column(axis=0)별로 작동하는 함수가 아니라, 각 요소(element)별로 작동
마치 선형대수에서 벡터에 스칼라를 연산하면, 벡터의 요소 하나하나에 해당 연산을 해주는 것처럼(elementwise) 적용하는 DataFrame의 각 요소마다 커스텀 함수(반드시 Single vaule를 반환하는)를 수행한다고 보면 된다. applymap에 인자로 전달하는 커스텀함수가 Single value로부터 Single value를 반환한다는 점이 중요하다

In [51]:
# series의 최대값과 최소값의 차이를 계산
f = lambda x:x.max() - x.min()
df.apply(f)

b    1.188439
d    0.904417
e    1.757449
dtype: float64

In [52]:
# 각 행에 대해서 수행
df.apply(f,axis='columns')

서울    1.589124
부산    1.028805
인천    1.019155
대구    1.072742
dtype: float64

In [53]:
# Q. 적절한 사용자 함수 혹은 람다 함수를 생성해서 df에 그 함수를 적용한 결과를 출력하세요.

f = lambda x: x.sum() / x.count()

a = np.abs(df).apply(f, axis = 1)
a

서울    0.582870
부산    0.404899
인천    0.473962
대구    0.380696
dtype: float64

In [54]:
a= lambda x:(x.max() + x.min())/2
# df.apply(a, axis='index')
df.apply(a)

b   -0.408328
d   -0.071086
e   -0.329277
dtype: float64

In [55]:
# 여러값을 가진 series 변환
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])

df.apply(f)

b         d         e
min -1.002547 -0.523295 -1.208001
max  0.185892  0.381123  0.549448

In [56]:
# Q. 실수값을 문자열 포맷으로 변환(소수점 2자리)

format = lambda x: '%.2f' %x
df.applymap(format)

b      d      e
서울  -0.16   0.38  -1.21
부산   0.19   0.38  -0.65
인천  -1.00  -0.40   0.02
대구   0.07  -0.52   0.55

In [57]:
# map함수는 series에만 적용

df['e'].map(format)

서울    -1.21
부산    -0.65
인천     0.02
대구     0.55
Name: e, dtype: object